cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/952375157783/jtf-queue
server:
  port: 9192

logging:
  level:
    org:
      springframework:
        cloud:
          aws: DEBUG
